### ISSUE TITLE
Create a SFW version

### ISSUE THREAD

**Issue by Vista2003** [larrysalibra/WearAFuckingMask.com#3]
Make an SFW version to allow it to be seen by more people.

**Comment by larrysalibra** [comment]
Thanks for the feedback. 

I understand that some places block content with "bad" language. I think the language is important to making the point, so I won't make a censored version.

**Comment by shayneoneill** [comment]
Theres nothing really stopping someone from forking this and creating a politer version. 

Frankly I'd take out the whack nonsense about the WHO and the whacker nonsense about price controls.

**Comment by larrysalibra** [comment]
Two SFW options:
https://wearafuckingmask.com/sfw/
https://wearafabulousmask.com/
